### ISSUE TITLE
unexpected token readFile

### ISSUE THREAD

**Issue by enuggetry** [sakshamsaxena/sails-hook-jbvcs#20]
I got this error on execution of jbvcs.
Not sure if I have the command line right???

```
[jbrowser@localhost sails-hook-jbvcs]$ sudo jbvcs -u enuggetry -r jbvcs-test -w 1000 0

/usr/lib/node_modules/sails-hook-jbvcs/lib/cli.js:57
                                        fs.readFile(__dirname + '/user.config', 'utf-8', (err, data) => {
                                                                                                      ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
[jbrowser@localhost sails-hook-jbvcs]$ ls
lib  LICENSE  node_modules  package.json  README.md  test
[jbrowser@localhost sails-hook-jbvcs]$
```

**Comment by enuggetry** [comment]
Suggest you also add a sample command line into your readme.md.

**Comment by sakshamsaxena** [comment]
I've used Arrow functions of ES6 here. Use node v4 or greater perhaps. 
On 22-Aug-2016 11:00 AM, Eric Y <notifications@github.com> wrote:I got this error on execution of jbvcs.
Not sure if I have the command line right???

[jbrowser@localhost sails-hook-jbvcs]$ sudo jbvcs -u enuggetry -r jbvcs-test -w 1000 0

/usr/lib/node_modules/sails-hook-jbvcs/lib/cli.js:57
                                        fs.readFile(__dirname + '/user.config', 'utf-8', (err, data) => {
                                                                                                      ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
[jbrowser@localhost sails-hook-jbvcs]$ ls
lib  LICENSE  node_modules  package.json  README.md  test
[jbrowser@localhost sails-hook-jbvcs]$

**Comment by enuggetry** [comment]
I have node v6.4.0.

**Comment by enuggetry** [comment]
I just resolved this by changing to the function() notation
