### ISSUE TITLE
Setup docs need more work.

### ISSUE THREAD

**Issue by enuggetry** [sakshamsaxena/sails-hook-jbvcs#25]
The setup documentation needs work because it does not specify any of the limitations, such as:
- expected jbrowse directory, which is hardcoded.
- expected target directory layout.
- examples of commands would be helpful.  (i.e. if you run this, you expect to see this.)

I was more or less able to figure out these, but I had to dig for it.

**Comment by sakshamsaxena** [comment]
First two points were often brought up in our meetings, but okay I'll mention this in the docs. Also, the commands get listed if you simply run ```jbvcs``` which is mentioned in the Readme.

**Comment by sakshamsaxena** [comment]
I did mention some of it already in the docs [here](https://github.com/sakshamsaxena/sails-hook-jbvcs/wiki/API-Documentation#jbvcsclonetags-n).
